[package]
name = "valloc"
version = "0.0.2"
edition = "2021"

[lib]
name = "valloc"
crate-type = ["lib"]

[features]
C = []

[[example]]
crate-type = ["bin"]
name = "c_test"

[[example]]
name  = "valloc_shell"
test  = false
bench = false

[dependencies]
lazy_static = "1.4.0"
