[package]
name = "valloc"
version = "0.1.0"
edition = "2021"

[lib]
name = "valloc"
crate-type = ["staticlib"]

[[example]]
crate-type = ["bin"]
name = "c_test"

[[example]]
name  = "valloc_shell"
test  = false
bench = false

[dependencies]
