[package]
name = "valloc"
version = "0.0.2"
edition = "2021"

[lib]
name = "valloc"
crate-type = ["staticlib"]

[[example]]
crate-type = ["bin"]
name = "c_test"

[[example]]
name  = "valloc_shell"
path  = "examples/valloc_shell.rs"
test  = false
bench = false
